# Generated by Django 5.0.2 on 2024-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('studentBranch', models.CharField(max_length=50)),
                ('studentEmail', models.CharField(max_length=50)),
                ('studentSemester', models.CharField(max_length=50)),
            ],
        ),
    ]
