# Generated by Django 5.0.2 on 2024-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=50)),
                ('teacherSubject', models.CharField(max_length=50)),
                ('teacherEmail', models.CharField(max_length=50)),
            ],
        ),
    ]
